### ISSUE TITLE
Can I help? I am super-interested in this project!

### ISSUE THREAD

**Issue by EnricoDiLello** [StatMixedML/GBMLSS#1]
Hi, I hope you're well and keeping safe in this crazy year. Is development still happening? I'd be happy to help, as I am very interested what this project can achieve. I am not the best Python programmer, but I use it routinely at work and I have a background in Bayesian Statistics. Cheers.

**Comment by StatMixedML** [comment]
@EnricoDiLello Thanks for your interest and you are well!

I am not sure if you can contribute since I am still struggling with the multivariate parameter optimization problem discussed here https://github.com/StatMixedML/XGBoostLSS/issues/8

If you want to contribute, you can look into it. Appreciate your initiative.
